<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dokter Area_simple-search</name>
   <tag></tag>
   <elementGuidId>f57b876d-2bb0-4744-9851-a943b6a7e5ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#simple-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='simple-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>068b7c10-c370-4503-baaf-0f9fdde6f5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e338b224-6dcf-4d25-992a-8416ed66224d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>simple-search</value>
      <webElementGuid>b25b1ab0-23ba-4df5-ae85-1cac79fddfe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-none rounded-lg h-[54px] bg-web-green-200  placeholder-white text-white</value>
      <webElementGuid>645c58fb-0456-40e8-aa20-191db53a7928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pencarian</value>
      <webElementGuid>32967ccf-2aa9-4aee-8725-6d7d0c73bd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simple-search&quot;)</value>
      <webElementGuid>d850e8c1-312f-4429-a1a0-743513936ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='simple-search']</value>
      <webElementGuid>cca982f8-cd3b-4453-8bc6-81e01484645f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f00f439b-9973-4d87-a844-aff118866cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'simple-search' and @placeholder = 'Pencarian']</value>
      <webElementGuid>1731fb5d-01a8-43d4-81b7-ad17f4a10a9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
