<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dokter Area_simple-search</name>
   <tag></tag>
   <elementGuidId>27692e3b-c93d-4f3a-98ee-4f424aca78d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > section > div.grid.lg\:grid-cols-3.md\:grid-cols-2.sm\:grid-cols-1.gap-10 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='simple-search']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'simple-search' and @placeholder = 'Pencarian']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76697178-1fae-4eb5-96ba-1be1438e9e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fea2641a-b19a-4471-a8fb-84805da45c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>simple-search</value>
      <webElementGuid>c050b495-245a-4639-8736-e85473b47512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-none rounded-lg h-[54px] bg-web-green-200  placeholder-white text-white</value>
      <webElementGuid>9d59f11b-380b-40a6-b6d5-e225723298a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pencarian</value>
      <webElementGuid>043badf2-daa4-456d-bb83-8084ecdc6ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simple-search&quot;)</value>
      <webElementGuid>ae0d46c6-323a-477a-860d-789df055bb76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='simple-search']</value>
      <webElementGuid>3c5da373-9317-4741-bdac-e614bd818a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ec1ccc12-cfb2-4e20-b9bd-0e1d0deef604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'simple-search' and @placeholder = 'Pencarian']</value>
      <webElementGuid>683f5cd8-7f23-43b0-88e3-8b5f54ff094f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
