<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dokter Area_notFoundArticle</name>
   <tag></tag>
   <elementGuidId>c4e8e8a2-90b7-42b2-8f7e-497e6f06d453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > section > div.grid.lg\:grid-cols-3.md\:grid-cols-2.sm\:grid-cols-1.gap-10 > div > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='simple-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1da338e-0916-4e13-a281-42f8d23a09de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>simple-search</value>
      <webElementGuid>36f63c8a-d902-4e26-9f6f-f776c2500f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-none rounded-lg h-[54px] bg-web-green-200  placeholder-white text-white</value>
      <webElementGuid>505f6269-1d70-42a3-b850-339f9f444ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pencarian</value>
      <webElementGuid>b19f3b9c-222a-4475-94be-78a24beeb851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77f68fcf-bad6-4841-94db-22ceff3f55d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simple-search&quot;)</value>
      <webElementGuid>a46a49f6-4de4-4cc8-b25f-56f6b63355bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='simple-search']</value>
      <webElementGuid>a55fb88b-01fb-421c-987b-26e4ea4559ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>64ddc957-8b48-486c-b42f-b7cc35ac4634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'simple-search' and @placeholder = 'Pencarian' and @type = 'text']</value>
      <webElementGuid>6b08f0f6-0569-431f-ba60-e23b4d7dc804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
