<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dokter Area_simple-search_1</name>
   <tag></tag>
   <elementGuidId>c4e8e8a2-90b7-42b2-8f7e-497e6f06d453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#simple-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='simple-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>029ac9cd-b2c0-45ed-b155-44281e62b844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>simple-search</value>
      <webElementGuid>bf27c9cb-5ed7-49e4-9bfc-6ba7fc56f329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-none rounded-lg h-[54px] bg-web-green-200  placeholder-white text-white</value>
      <webElementGuid>9f53a703-efff-4948-afc5-9d26554f8519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pencarian</value>
      <webElementGuid>b4b1f0ed-0f9a-4e47-aa69-b79c585c85c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e78a31c3-3e63-45fb-8364-009823d867e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simple-search&quot;)</value>
      <webElementGuid>fded97c0-37a8-4377-b6fe-146e279737b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='simple-search']</value>
      <webElementGuid>05524f7a-5c5b-42bd-a3f5-57b1de8b4bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f6092b9d-7c1d-453c-b7d5-12b58a21791c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'simple-search' and @placeholder = 'Pencarian' and @type = 'text']</value>
      <webElementGuid>6726b9bb-1f1b-45f7-8103-2451cb2a532b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
