<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail</name>
   <tag></tag>
   <elementGuidId>53c4cb9c-e273-48ee-a815-b30ffc5bd219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Detail')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c5b8b8d-ef29-4b6f-9a0e-dd1165732fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-normal font-poppins text-neutral-0 text-xs/[120%] text-left  bg-web-green-300 hover:bg-web-green-400 rounded-xl pt-4 pr-3 pb-4 pl-3 flex flex-row gap-2.5 items-center justify-center shrink-0 w-[84px] h-[31px] relative</value>
      <webElementGuid>9213d10a-856d-428e-b57a-847f4ae40d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/detail-dokter/41</value>
      <webElementGuid>48a137cf-da14-431b-bc69-6ac184d1c1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>756d01e7-5ddc-4d66-8372-57a2882dd701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;mx-auto bg-neutral-0 w-[1440px] h-[1000px] relative overflow-hidden&quot;]/div[@class=&quot;flex flex-col gap-[45px] items-start justify-start absolute left-[541px] top-[250px]&quot;]/div[@class=&quot;flex flex-col gap-[17px] items-start justify-start shrink-0 relative&quot;]/div[@class=&quot;flex flex-row flex-wrap gap-[45px] items-center justify-start shrink-0 relative&quot;]/div[@class=&quot;bg-neutral-0 rounded-[5px] shadow-[0_4px_4px_0_rgba(0,0,0,0.25)] flex flex-row gap-1.5 items-center justify-center shrink-0 w-[374px] h-[145px] relative&quot;]/div[@class=&quot;h-[134px] flex flex-col pb-[2px] items-start justify-between relative&quot;]/a[@class=&quot;font-normal font-poppins text-neutral-0 text-xs/[120%] text-left  bg-web-green-300 hover:bg-web-green-400 rounded-xl pt-4 pr-3 pb-4 pl-3 flex flex-row gap-2.5 items-center justify-center shrink-0 w-[84px] h-[31px] relative&quot;]</value>
      <webElementGuid>7d290c98-89da-4635-81f4-fe36f45274ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Detail')]</value>
      <webElementGuid>c2833f52-4a73-4bd9-90e4-e18774a8b793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dummydummy'])[1]/following::a[1]</value>
      <webElementGuid>98f53055-07dd-47c9-a559-75b96917a756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konsultasi online dengan dokter kami'])[1]/following::a[1]</value>
      <webElementGuid>8f4aa81e-0979-4642-8b28-09287f4d2491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spongebob Squarepants'])[1]/preceding::a[1]</value>
      <webElementGuid>536229af-6131-4844-bfd2-e1807ea9ee7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[2]/preceding::a[1]</value>
      <webElementGuid>4d2807ab-b1b7-4778-a3f5-b64f5a43ba82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>16a22170-88ec-4e58-a75f-e83ac2336a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/detail-dokter/41')]</value>
      <webElementGuid>3ca608da-776f-4547-a94d-f3c2ac8cdb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>3a992ad9-3b33-4151-a7da-fa2d7ae5a555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/detail-dokter/41' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>4a5c72d2-08e3-4ba9-9fe3-b18196be57d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
