<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dummydummydummy</name>
   <tag></tag>
   <elementGuidId>2b36c2f2-1c9d-4a7f-9e7b-fc6835fd0c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter Area'])[1]/following::div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ef897aa-efad-42e8-81de-989cb763e650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  mt-[100px] mb-[50px] flex flex-col items-center</value>
      <webElementGuid>b7f5b5f6-225f-4e58-870d-72268d269e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dummydummydummy</value>
      <webElementGuid>43853f49-5f06-4786-8680-5c502f4ef266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;mx-auto  max-w-[1440px]&quot;]/div[@class=&quot;mt-[100px] mb-[50px] flex flex-col items-center&quot;]</value>
      <webElementGuid>a0128936-f3cb-4035-815a-5476b12552b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter Area'])[1]/following::div[6]</value>
      <webElementGuid>4ea5b327-f0a7-4ae4-bc60-f1541a5479b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter'])[1]/following::div[6]</value>
      <webElementGuid>8972c554-7349-463a-9021-11da61e915fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>6c5bcbb2-0f3b-4ae4-af53-0d5f4de6f0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'dummydummydummy' or . = 'dummydummydummy')]</value>
      <webElementGuid>5311893e-aa18-414e-87ae-e747bc6bc4f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
