<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sebelumnya</name>
   <tag></tag>
   <elementGuidId>4e38aea0-3806-4675-9c9e-8d5deab8895f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.border.py-2.px-6.rounded-l-lg.bg-neutral-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Berlanjut'])[2]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>03f29a3a-3b85-4e34-94bf-29132130ac23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border py-2 px-6 rounded-l-lg bg-neutral-0</value>
      <webElementGuid>4895e563-5c36-4265-9b0a-055eb56d2276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sebelumnya</value>
      <webElementGuid>4b15f755-6fd6-4853-9bf0-a57b5071d7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;h-full w-full&quot;]/main[@class=&quot;lg:pl-20 h-full&quot;]/div[@class=&quot;h-full&quot;]/div[@class=&quot;max-w-[1440px] mx-auto px-[32px]&quot;]/div[@class=&quot;flex justify-between items-center mt-10 mb-24&quot;]/div[2]/button[@class=&quot;border py-2 px-6 rounded-l-lg bg-neutral-0&quot;]</value>
      <webElementGuid>7d7a7663-8915-4ce7-bbc3-1f181bcfb2de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berlanjut'])[2]/following::button[1]</value>
      <webElementGuid>52807b5c-3476-4341-8b03-1e13ac3f1f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::button[1]</value>
      <webElementGuid>89e596d1-e8eb-4f94-b6d3-6e0efa817ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sebelumnya']/parent::*</value>
      <webElementGuid>45c5b51b-0421-41ae-9ec4-026af7123938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>10c63326-a688-4413-9315-04608328298a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Sebelumnya' or . = 'Sebelumnya')]</value>
      <webElementGuid>fbf5fd1c-a0fc-444c-9c7e-9664567a3179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
