<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect</name>
   <tag></tag>
   <elementGuidId>4d138f4d-c389-40f3-9fa0-2130f7699a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>rect:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>974d93e6-e786-49dd-aa02-49ec181e3208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>44e240f4-44e8-467a-8f88-7afb54387424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>1bec3f2d-487f-4d75-942c-8e7be8d97c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>4d820270-ec13-4ef6-a6ff-5078863c6c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ba3d1146-a481-4d6e-902f-dc2dcaf8249a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3d8065ba-f99b-4df4-916b-ef05d9334144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>730f741e-5249-4488-a782-61a3b2725b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a337682b-3af1-412c-8ad1-ed9e2eb017a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;h-full w-full&quot;]/nav[@class=&quot;z-10 bg-web-green-300 m-0 p-0&quot;]/div[@class=&quot;min-w-[1440px] flex flex-wrap items-center justify-between mx-auto p-[22px]&quot;]/div[@class=&quot;flex flex-wrap items-center&quot;]/button[1]/svg[1]/rect[4]</value>
      <webElementGuid>2aaeb990-9c2f-44ad-aa24-af3b0334a2c6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
