<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_12510</name>
   <tag></tag>
   <elementGuidId>6856b0ad-296b-4fbc-ae4a-b0a74b68ef88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#data-per-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='data-per-page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a45fb2b9-e64d-4def-b1d1-baeb80371b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data-per-page</value>
      <webElementGuid>f00e3314-9e74-4ba3-89bc-ab6245033e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appearance-none bg-white border border-gray-300 rounded-xl px-4 py-2 pr-8 leading-tight focus:outline-none focus:border-blue-500 mx-5</value>
      <webElementGuid>a6adbaf8-b34c-41ae-bd26-56251b69480f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12510</value>
      <webElementGuid>31ccf5d9-4341-43b0-bb51-817836e101bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-per-page&quot;)</value>
      <webElementGuid>6c3bc5fd-e0c3-40cc-a2c1-3c11a0939210</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='data-per-page']</value>
      <webElementGuid>f7305a22-d665-4401-b497-45ee20c51639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan'])[1]/following::select[1]</value>
      <webElementGuid>bc9fb97a-ce13-4345-953f-bee186026691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter Area'])[1]/following::select[1]</value>
      <webElementGuid>748a8be5-02a0-4c36-83f8-6079e4b55e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::select[1]</value>
      <webElementGuid>0ab63c6f-6b34-44ce-8011-3dd354fe6bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal'])[1]/preceding::select[1]</value>
      <webElementGuid>e16afd9a-9174-4cb3-978b-5b052ccc036e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>bfe1d8f5-b482-4847-8db4-de0cfe2c8fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'data-per-page' and (text() = '12510' or . = '12510')]</value>
      <webElementGuid>5264381f-948b-4816-9aec-bd337c5a3da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
