<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>487677dd-57c7-4c0e-8096-bc5b6e9bc5b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter Area'])[1]/preceding::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e10cdf42-42a6-4ae1-91c7-d6201679c479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>33.75px</value>
      <webElementGuid>e97a3f94-b0f9-482d-a918-fe4e1496a939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>26.25px</value>
      <webElementGuid>c9ce28c5-4419-4ada-a38f-bac7fd07b443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 26 18</value>
      <webElementGuid>949cd58c-961d-4d03-8397-9c4e20397f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f966287f-0842-4da4-adfc-4d5e1dcd274d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>7b60e528-dcfd-4fd5-83d5-50e81f754120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;h-full w-full&quot;]/nav[@class=&quot;z-10 bg-web-green-300 m-0 p-0&quot;]/div[@class=&quot;min-w-[1440px] flex flex-wrap items-center justify-between mx-auto p-[22px]&quot;]/div[@class=&quot;flex flex-wrap items-center&quot;]/button[1]/svg[1]</value>
      <webElementGuid>ef5eb37a-db81-40e7-b7ad-742bb410358c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter Area'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>f67e66ce-a329-44c0-bab2-c29caa9dc00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>5c7930f7-1001-4bb8-a4b2-7136e66223c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
