<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilih_sip</name>
   <tag></tag>
   <elementGuidId>37019464-ce7e-445d-b59f-f654a118992e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file-input-sip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#file-input-sip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe7bb3ee-3865-493b-98ce-225950b95b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file-input-sip</value>
      <webElementGuid>6a8f0573-20e6-4995-af14-34dbbb358cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>7bf067d8-8a75-4683-b424-f38dd8ce8f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sip</value>
      <webElementGuid>d59cfaf2-c893-4622-817c-6e40440f996f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file-input-sip&quot;)</value>
      <webElementGuid>c88b75ef-cad4-4f3f-a9e2-ce5b216c0719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file-input-sip']</value>
      <webElementGuid>50b99c60-27c0-4cfe-bd3e-7052a6da3ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>6e460adb-26f0-49b8-a4fe-63e0daf51633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'file-input-sip' and @type = 'file' and @name = 'sip']</value>
      <webElementGuid>c91fab8a-a955-4f82-9a09-ff8eb68d9354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
