<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_practice_address</name>
   <tag></tag>
   <elementGuidId>1a801bbf-8737-4f92-8e54-1a2e8f3ca0af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='practice_address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;practice_address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4acac153-6e04-4a18-889b-d7ec662a04ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tempat Praktik Sekarang</value>
      <webElementGuid>33ea1ab1-e3a7-4979-baa5-c12db37c3771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full  border  rounded-lg border-neutral-70 </value>
      <webElementGuid>eba1527c-ba3a-425e-be8d-168f564711ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>907ea65e-0ca2-40ef-92b6-d1399b04ac10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>practice_address</value>
      <webElementGuid>e3d2e09c-8375-49e1-a4c4-0457dd072fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;min-screen-2xl h-screen flex bg-gray-500&quot;]/div[@class=&quot;w-1/2 bg-neutral-0 flex flex-col justify-center&quot;]/div[@class=&quot;w-[480px] flex flex-col gap-8 mx-auto text-center&quot;]/form[@class=&quot;flex flex-col gap-8&quot;]/div[7]/input[@class=&quot;w-full  border  rounded-lg border-neutral-70&quot;]</value>
      <webElementGuid>afb52cf8-1998-45f5-9b4d-e505cc6a6d3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='practice_address']</value>
      <webElementGuid>08d1fe6c-b362-44e4-979f-296acb83366a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>1f96724a-6b16-4735-bc49-bcf0efe92def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tempat Praktik Sekarang' and @type = 'text' and @name = 'practice_address']</value>
      <webElementGuid>3bb318a8-88f2-4b76-8111-8a40f4ebde5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
