<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilih File_cv</name>
   <tag></tag>
   <elementGuidId>def9034b-9dad-4329-87c0-406d302302cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file-input-cv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#file-input-cv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfa4213c-2b53-43d5-ab6d-169611ae6740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file-input-cv</value>
      <webElementGuid>14acb9e4-4f78-4091-a748-d6279d38e8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>27ac6177-0fe1-44fc-9a3e-8f469a58b15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cv</value>
      <webElementGuid>4fc58497-dd67-41a5-be7a-6fe143a264b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file-input-cv&quot;)</value>
      <webElementGuid>6665026a-7678-49eb-88a5-456b0cc5ecc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file-input-cv']</value>
      <webElementGuid>28f7e4eb-ab16-4b63-8935-ef4be6ba915a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0a5e726f-915f-4f28-a903-2d1d879f8443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'file-input-cv' and @type = 'file' and @name = 'cv']</value>
      <webElementGuid>d75a3d90-dbff-4b67-ae26-8f399ab2a4c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
