<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilih_ijazah</name>
   <tag></tag>
   <elementGuidId>9260da63-0e41-40af-88aa-6438bc73e50d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file-input-ijasah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#file-input-ijasah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1585df3-73a2-42ab-813b-ac622c386aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file-input-ijasah</value>
      <webElementGuid>f4039131-580c-4e98-a221-2975a1963931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>4458ca19-5bc7-4ba9-91ce-47442ec8bbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ijazah</value>
      <webElementGuid>eb697054-7d0d-4268-bf8a-e80111d20e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file-input-ijasah&quot;)</value>
      <webElementGuid>cbd89b03-e4cd-4180-ad3f-d275877b578a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file-input-ijasah']</value>
      <webElementGuid>9a7ffb10-af6f-4b6c-856e-434cfafa27c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>06f82a09-faf3-4cae-b3c9-3a7adc8883ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'file-input-ijasah' and @type = 'file' and @name = 'ijazah']</value>
      <webElementGuid>98d0f562-3e1d-4c53-abab-2b958b21956a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
