<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Capture object_str_number</name>
   <tag></tag>
   <elementGuidId>70c4fc38-d8ec-44ed-8d1d-334830f60143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='str_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;str_number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae8f272f-0a51-4a6d-9837-822f2beb93b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No STR*</value>
      <webElementGuid>e8b75f3e-db6d-4f82-9706-7c2b7682faac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full  border  rounded-lg border-neutral-70 </value>
      <webElementGuid>a95e7e6b-5f7c-4cee-8b61-9d419d70d72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>152e6ef4-a963-4bcc-98bf-22fd3f60d5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1234567</value>
      <webElementGuid>14a1b50c-767d-47fe-b8b0-5dfc795b1011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>str_number</value>
      <webElementGuid>1c0c1134-8a0e-4298-984f-21364a3e1117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;min-screen-2xl h-screen flex bg-gray-500&quot;]/div[@class=&quot;w-1/2 bg-neutral-0 flex flex-col justify-center&quot;]/div[@class=&quot;w-[480px] flex flex-col gap-4 mx-auto text-center&quot;]/form[@class=&quot;flex flex-col gap-8&quot;]/div[8]/input[@class=&quot;w-full  border  rounded-lg border-neutral-70&quot;]</value>
      <webElementGuid>b4b43ba3-8cc9-4735-9dbd-5b7e70a3b8d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='str_number']</value>
      <webElementGuid>7393413d-9d1a-43cf-a9f5-b7faacdcaf5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>d0e2e332-c371-4a97-b537-16da1bcda40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'No STR*' and @type = 'text' and @name = 'str_number']</value>
      <webElementGuid>09cbeace-7773-4db5-9953-a2197bde6801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
