<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Jenis KelaminLaki-LakiPerempuan</name>
   <tag></tag>
   <elementGuidId>426b3071-3f1c-4cb6-af85-cb952efe4d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='gender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;gender&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9de43283-11d1-490d-b48d-e742cad30a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full  border  rounded-lg border-neutral-70 </value>
      <webElementGuid>92d95826-97ce-4e8e-a71a-785a5e0f96f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>14a3c3eb-ba62-42f3-ab6f-b4e7024e80a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Jenis KelaminLaki-LakiPerempuan</value>
      <webElementGuid>79430aa9-b0b3-49d2-98ed-e9d1664cc209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;min-screen-2xl h-screen flex bg-gray-500&quot;]/div[@class=&quot;w-1/2 bg-neutral-0 flex flex-col justify-center&quot;]/div[@class=&quot;w-[480px] flex flex-col gap-4 mx-auto text-center&quot;]/form[@class=&quot;flex flex-col gap-8&quot;]/div[4]/select[@class=&quot;w-full  border  rounded-lg border-neutral-70&quot;]</value>
      <webElementGuid>65bbdae6-496e-4556-ab1b-12d571a1a231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='gender']</value>
      <webElementGuid>1ee21677-0958-49d2-9f22-6b72061b806d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::select[1]</value>
      <webElementGuid>9e96a568-12a7-4dc7-9442-b722508ea1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::select[1]</value>
      <webElementGuid>4c2abda7-c713-4360-b8cf-98a618f41020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>bd92a1d4-0250-41b4-981d-ed342ce8a5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'gender' and (text() = 'Pilih Jenis KelaminLaki-LakiPerempuan' or . = 'Pilih Jenis KelaminLaki-LakiPerempuan')]</value>
      <webElementGuid>5e133772-735d-4cc4-8a55-6aba921b7a98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
