<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hapus</name>
   <tag></tag>
   <elementGuidId>928f0463-35d0-45df-b9d8-ad15d3f190fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[4]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59a6e370-ea26-48cb-aad2-7c54abf86574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-normal rounded-lg gap-3 flex justify-center bg-[#A12D28] hover:bg-[#A12D28] hover:drop-shadow-md text-white py-3 px-4</value>
      <webElementGuid>a4d3674b-180a-4507-af60-4558047bbc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus</value>
      <webElementGuid>54e7f0ad-43a6-48da-b05a-e64943962335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;h-full w-full&quot;]/main[@class=&quot;h-full&quot;]/div[@class=&quot;h-full&quot;]/div[@class=&quot;mx-auto mb-5 max-w-[1440px]&quot;]/table[@class=&quot;border-collapse borde ml-3 border-success-green-100 w-[1370px]&quot;]/tbody[1]/tr[4]/td[@class=&quot;border border-success-green-100 text-center flex justify-center px-10 gap-2&quot;]/button[@class=&quot;font-normal rounded-lg gap-3 flex justify-center bg-[#A12D28] hover:bg-[#A12D28] hover:drop-shadow-md text-white py-3 px-4&quot;]</value>
      <webElementGuid>74c406fe-d7b1-4ef3-b2c1-c405790faf63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[4]/following::button[1]</value>
      <webElementGuid>69106ab3-809f-4c17-87c4-09075c03a35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ditinjau'])[3]/following::button[2]</value>
      <webElementGuid>aa48e9f2-b632-4346-89f2-0d2ed5b2c2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa yang harus dilakukan ketika depresi ?'])[1]/preceding::button[1]</value>
      <webElementGuid>1523b6a4-69de-43f9-b09a-d219c770e111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stress'])[1]/preceding::button[1]</value>
      <webElementGuid>30a56a5a-60f4-4588-b1c6-4037f160108e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/button</value>
      <webElementGuid>4551cb59-f1c6-4c5c-b036-ff20f0e4acef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Hapus' or . = 'Hapus')]</value>
      <webElementGuid>6c4fd218-5352-465b-9539-a1f7c00c8ace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
