<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maksimal 250 Karakter_w-full rounded-lg_1</name>
   <tag></tag>
   <elementGuidId>58639f69-cd13-44c3-b6ce-7b9b9e2421ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.w-full.rounded-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83ea185a-f57e-4f86-9e4b-fdb263e62401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38b4ad35-f795-43bb-8b70-d644620ae55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Judul Artikel</value>
      <webElementGuid>793c4c2b-04df-4ca6-aa0e-4a5ba51258f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full rounded-lg</value>
      <webElementGuid>515858b0-2f7a-4df3-9688-ba5f86e686b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>e16806c4-4c54-4201-9bb3-7d3418ec40c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;h-full w-full&quot;]/main[@class=&quot;lg:pl-20 h-full&quot;]/div[@class=&quot;h-full&quot;]/section[@class=&quot;mx-auto max-w-[1440px]&quot;]/form[1]/div[@class=&quot;mx-24&quot;]/div[1]/input[@class=&quot;w-full rounded-lg&quot;]</value>
      <webElementGuid>662bb00b-f690-4cf0-bca0-34c84302f263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>841262f4-4f6f-4d9d-b349-e7163c981a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5c6463a3-63d1-4c34-ae40-dea53b0be486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Judul Artikel']</value>
      <webElementGuid>c315bfc7-7864-43da-891d-cd2fc4d38103</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
