<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>e540e9fe-dc02-455d-b1e0-094628d151d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter Area'])[1]/preceding::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>d800514c-137d-4ec3-89c3-99aaf123fd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>33.75px</value>
      <webElementGuid>9507c6c5-c181-41fa-9b53-686ef1d108d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>26.25px</value>
      <webElementGuid>96d1e35f-0040-4f1c-86ab-4742f42945db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 26 18</value>
      <webElementGuid>1488d103-e1ee-4468-bec6-62cb55f5a605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e3995cb0-276a-4b84-a516-d4c73c812669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>9ebeec1c-2aa7-4574-8c9a-bb76172c0696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;h-full w-full&quot;]/nav[@class=&quot;z-10 bg-web-green-300 m-0 p-0&quot;]/div[@class=&quot;min-w-[1440px] flex flex-wrap items-center justify-between mx-auto p-[22px]&quot;]/div[@class=&quot;flex flex-wrap items-center&quot;]/button[1]/svg[1]</value>
      <webElementGuid>4882a0af-0c86-493d-b834-bfd52bfff535</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter Area'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>7c4099a6-8ec1-4a74-ba61-f3ce59ccfd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>f60048b8-5035-4fda-adf1-e0fd57faea2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
